### ISSUE TITLE
Add .stark display to JediSwap

### ISSUE THREAD

**Issue by fricoben** [jediswaplabs/jediswap-interface#129]
**Is your feature request related to a problem? Please describe.**

Hello ! 

I'm Ben cofounder of starknet ID and We would love to add a small integration of stark domains to your application as all the big mainnet applications are already doing it ! 

<img width="1168" alt="Capture d’écran 2023-02-25 à 09 49 35" src="https://user-images.githubusercontent.com/78437165/221348070-8871039b-6d0a-4a75-93e0-8f307e0d8619.png">

**Describe the solution you'd like**
It's really easy to do and would look something like this :

<img width="455" alt="Capture d’écran 2023-02-25 à 09 56 07" src="https://user-images.githubusercontent.com/78437165/221348324-af36df18-7a2c-4e07-94b1-c7055a596a86.png">

We simply have to call the contract/server depending on the solution you prefer to implement. We could even add a profile image like you can see in the braavos wallet. 

Here is an example: 

<img width="257" alt="Capture d’écran 2023-02-25 à 09 59 59" src="https://user-images.githubusercontent.com/78437165/221348514-2ce26fae-569b-40eb-b287-e9593f7fd6f6.png">

**Describe alternatives you've considered**
We can use several technical alternatives : 
1) Use Starknet.js functions
2) Use Starknet.js functions
3) Do it manually with starknet.js/starknet react (depending on what you guys are using.
4) Use the starknet id indexer (it's not decentralized but for that kind of usage it's perfect)
5) The starknet id SDK that will be available soon

**Comment by 0xEniotna** [comment]
Let me try something for this one !

**Comment by 0xEniotna** [comment]
Hey @retroboydev, it appears that my PR was missing a little something. I use the same endpoint to fetch the domain for both mainnet & testnet.
I have a PR ready to fix the issue

**Comment by princearoragithub** [comment]
This is done.
