### ISSUE TITLE
Feat: Add Bridge - Part 1

### ISSUE THREAD

**Issue by dhruvkelawala** [jediswaplabs/jediswap-interface#21]
- [ ]  Add /bridge route to react-router
- [ ]  Add Bridge to Navbar, which on click redirects to /bridge route
- [ ]  Create the initial Bridge UI for ArgentX and Metamask connection 
https://www.figma.com/file/MDQ2gpTlxoQnF2WUQMDJme/JediSwap---Webapp?node-id=2676%3A4675
- [ ] Add Metamask connect functionality using ethers.js (https://docs.ethers.io/v5/) and web3-react (v6) library (https://github.com/NoahZinsmeister/web3-react/tree/v6). Use Mesh finance repo for understanding how it works  https://gitlab.com/meshfinance/mesh-finance-website/-/blob/new_ui/src/main.tsx#L45

**Comment by upraisertech** [comment]
> * [ ]   Add /bridge route to react-router
> * [ ]   Add Bridge to Navbar, which on click redirects to /bridge route
> * [ ]   Create the initial Bridge UI for ArgentX and Metamask connection
>   https://www.figma.com/file/MDQ2gpTlxoQnF2WUQMDJme/JediSwap---Webapp?node-id=2676%3A4675
> * [ ]  Add Metamask connect functionality using ethers.js (https://docs.ethers.io/v5/) and web3-react (v6) library (https://github.com/NoahZinsmeister/web3-react/tree/v6). Use Mesh finance repo for understanding how it works  https://gitlab.com/meshfinance/mesh-finance-website/-/blob/new_ui/src/main.tsx#L45

 please assigne this to me, if no one is working on it.
