### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by dhruvkelawala** [jediswaplabs/jediswap-interface#22]
Let's cleanup code before making this repo public

- [ ] Remove all console.logs
- [ ] Remove Comments which are not needed
- [ ] Remove all instances of Uniswap or replace them with Jediswap wherever needed

**Comment by upraisertech** [comment]
Please assign me to do this

**Comment by HashRei** [comment]
Hey @upraisertech, is this already done?

**Comment by rohitgoyal** [comment]
@HashRei It is not done yet. Feel free to pick it up and submit a PR :)
