### ISSUE TITLE
Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by vnaysngh-mudrex** [jediswaplabs/jediswap-interface#227]
### Description

we are getting heap allocation issue for sentry job.

https://github.com/jediswaplabs/jediswap-interface/actions/runs/6119340961/job/16609097525

**Comment by retroboydev** [comment]
fixied in https://github.com/jediswaplabs/jediswap-interface/commit/0240d18651904fa5b21959247daa704bb3dc3520
